version: '3.9'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - data_db:/data/db
  pyapp:
    build: .
    volumes:
      - ./py_code:/usr/py_code
volumes:
  data_db:
    external: true
